[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=3.4.3",
    "httpx>=0.28.1",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "websockets>=15.0.1",
]
